# Generated by Django 5.1.3 on 2025-02-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('valor_recompensa', models.CharField(max_length=255)),
                ('id_personaje', models.IntegerField()),
                ('id_reputacion', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiempoMinijuego',
            fields=[
                ('id_tiempo_minijuegos', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_minijuegos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minijuego',
            fields=[
                ('id_minijuegos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_minijuego', models.CharField(max_length=255)),
                ('descripcion_minijuego', models.TextField()),
                ('id_tiempo_minijuegos', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_recompensa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_minijuegos.recompensa')),
            ],
        ),
    ]
