# Generated by Django 5.1.3 on 2025-02-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_jugador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='id_personaje_personalizacion',
        ),
    ]
