# Generated by Django 5.1.3 on 2025-02-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_jugador', '0002_remove_personaje_id_personaje_personalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='tiempo_juego',
            field=models.DurationField(),
        ),
    ]
